"use client"
import { createContext, useContext, useState, ReactNode } from "react";

type LanguageContextType = {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState("en");

 const translations = {
  en: {
    "Helping 2M+ farmers discover schemes": "Helping 2M+ farmers discover schemes",
    "Farmer Miss Benefits <br/> Worth  50000 Every  Year": "Farmer Miss Benefits Worth ₹50,000 Every Year",
    "Find all government <br/>schemes in one place": "Find all government schemes in one place",
    "Continue with Mobile": "Continue with Mobile",
    "Choose What You Need Help With": "Choose What You Need Help With",
    "Instantly discover your eligible benefits in 30 seconds": "Instantly discover your eligible benefits in 30 seconds",
    "Government Schemes": "Government Schemes",
    "Get ₹6,000 – ₹50,000 yearly support from government schemes": "Get ₹6,000 – ₹50,000 yearly support from government schemes",
    "PM Kisan": "PM Kisan",
    "Subsidy Programs": "Subsidy Programs",
    "Equipment Support": "Equipment Support",
    "select": "Select",
    "Insurance Coverage": "Insurance Coverage",
    "Protect crops & get ₹10,000 – ₹2,00,000 claim support": "Protect crops & get ₹10,000 – ₹2,00,000 claim support",
    "✔ Crop Insurance": "✔ Crop Insurance",
    "✔ Health Coverage": "✔ Health Coverage",
    "✔ Accident Protection": "✔ Accident Protection",
    "Financial Support": "Financial Support",
    "Get loans up to ₹3,00,000 at lowest interest": "Get loans up to ₹3,00,000 at lowest interest",
    "✔ Kisan Credit Card": "✔ Kisan Credit Card",
    "✔ Farm Loans": "✔ Farm Loans",
    "✔ Interest Subsidy": "✔ Interest Subsidy",
    "How It Works": "How It Works",
    "Three simple steps to discover your schemes": "Three simple steps to discover your schemes",
    "Create Profile": "Create Profile",
    "Share basic information about your farm and eligibility criteria.": "Share basic information about your farm and eligibility criteria.",
    "Auto Matching": "Auto Matching",
    "Our system instantly matches you with all eligible government schemes.": "Our system instantly matches you with all eligible government schemes.",
    "Apply Instantly": "Apply Instantly",
    "Get complete guidance and apply directly through our platform.": "Get complete guidance and apply directly through our platform.",
    "Trusted by Millions of Farmers": "Trusted by Millions of Farmers",
    "Real adoption numbers from government schemes": "Real adoption numbers from government schemes",
    "PM Kisan Samman Nidhi": "PM Kisan Samman Nidhi",
    "11.8 Crore+ Farmers Applied": "11.8 Crore+ Farmers Applied",
    "Provides ₹6000 per year financial support directly to farmers’ bank accounts.": "Provides ₹6000 per year financial support directly to farmers’ bank accounts.",
    "👨‍🌾 9,50,00,000+ farmers benefited": "👨‍🌾 9,50,00,000+ farmers benefited",
    "💸 Avg Support Received: ₹6,000": "💸 Avg Support Received: ₹6,000",
    "⭐ Farmer Satisfaction: 4.5 / 5": "⭐ Farmer Satisfaction: 4.5 / 5",
    "Pradhan Mantri Fasal Bima Yojana": "Pradhan Mantri Fasal Bima Yojana",
    "36 Crore+ Applications": "36 Crore+ Applications",
    "Protects farmers against crop loss due to drought, flood, or natural disasters.": "Protects farmers against crop loss due to drought, flood, or natural disasters.",
    "👨‍🌾 3,20,00,000+ farmers benefited": "👨‍🌾 3,20,00,000+ farmers benefited",
    "💸 Avg Claim Settled: ₹18,400": "💸 Avg Claim Settled: ₹18,400",
    "⭐ Farmer Satisfaction: 4.0 / 5": "⭐ Farmer Satisfaction: 4.0 / 5",
    "Kisan Credit Card (KCC)": "Kisan Credit Card (KCC)",
    "7.3 Crore+ Farmers Applied": "7.3 Crore+ Farmers Applied",
    "Provides low‑interest loans for seeds, equipment, and farming needs.": "Provides low‑interest loans for seeds, equipment, and farming needs.",
    "👨‍🌾 4,80,00,000+ farmers benefited": "👨‍🌾 4,80,00,000+ farmers benefited",
    "💸 Avg Loan Issued: ₹1,12,000": "💸 Avg Loan Issued: ₹1,12,000",
    "⭐ Farmer Satisfaction: 4.3 / 5": "⭐ Farmer Satisfaction: 4.3 / 5",
    "Ready to Discover Your Schemes?": "Ready to Discover Your Schemes?",
    "Join thousands of farmers who are now getting the government support they deserve.": "Join thousands of farmers who are now getting the government support they deserve.",
    "Get Started Now": "Get Started Now",
    "Kisan Sahay": "Kisan Sahay",
    "Empowering farmers with government support discovery.": "Empowering farmers with government support discovery.",
    "Product": "Product",
    "Features": "Features",
    "Pricing": "Pricing",
    "Blog": "Blog",
    "Company": "Company",
    "About": "About",
    "Contact": "Contact",
    "Careers": "Careers",
    "Legal": "Legal",
    "Privacy": "Privacy",
    "Terms": "Terms",
    "Security": "Security",
    "Twitter": "Twitter",
    "Facebook": "Facebook",
    "LinkedIn": "LinkedIn"
  },
  hi: {
    "Helping 2M+ farmers discover schemes": "2M+ किसानों को योजनाओं का पता लगाने में मदद",
    "Farmer Miss Benefits <br/> Worth  50000 Every  Year": "किसानों के लिए हर साल ₹50,000 तक लाभ",
    "Find all government <br/>schemes in one place": "सभी सरकारी योजनाएँ एक ही जगह देखें",
    "Continue with Mobile": "मोबाइल के साथ जारी रखें",
    "Choose What You Need Help With": "आप किसमें मदद चाहते हैं चुनें",
    "Instantly discover your eligible benefits in 30 seconds": "30 सेकंड में अपनी पात्र योजनाएँ जानें",
    "Government Schemes": "सरकारी योजनाएँ",
    "Get ₹6,000 – ₹50,000 yearly support from government schemes": "सरकारी योजनाओं से ₹6,000 – ₹50,000 सालाना सहायता प्राप्त करें",
    "PM Kisan": "पीएम किसान",
    "Subsidy Programs": "सब्सिडी कार्यक्रम",
    "Equipment Support": "उपकरण सहायता",
    "select": "चुनें",
    "Insurance Coverage": "बीमा कवरेज",
    "Protect crops & get ₹10,000 – ₹2,00,000 claim support": "फसलों की सुरक्षा करें और ₹10,000 – ₹2,00,000 का दावा समर्थन प्राप्त करें",
    "✔ Crop Insurance": "✔ फसल बीमा",
    "✔ Health Coverage": "✔ स्वास्थ्य कवरेज",
    "✔ Accident Protection": "✔ दुर्घटना सुरक्षा",
    "Financial Support": "वित्तीय सहायता",
    "Get loans up to ₹3,00,000 at lowest interest": "न्यूनतम ब्याज पर ₹3,00,000 तक के ऋण प्राप्त करें",
    "✔ Kisan Credit Card": "✔ किसान क्रेडिट कार्ड",
    "✔ Farm Loans": "✔ कृषि ऋण",
    "✔ Interest Subsidy": "✔ ब्याज सब्सिडी",
    "How It Works": "यह कैसे काम करता है",
    "Three simple steps to discover your schemes": "अपनी योजनाएँ खोजने के लिए तीन आसान कदम",
    "Create Profile": "प्रोफाइल बनाएं",
    "Share basic information about your farm and eligibility criteria.": "अपने खेत और पात्रता जानकारी साझा करें।",
    "Auto Matching": "स्वचालित मिलान",
    "Our system instantly matches you with all eligible government schemes.": "हमारी प्रणाली तुरंत आपको सभी पात्र सरकारी योजनाओं से मिलाती है।",
    "Apply Instantly": "तुरंत आवेदन करें",
    "Get complete guidance and apply directly through our platform.": "पूरा मार्गदर्शन प्राप्त करें और सीधे हमारी प्लेटफ़ॉर्म से आवेदन करें।",
    "Trusted by Millions of Farmers": "लाखों किसानों द्वारा भरोसा किया गया",
    "Real adoption numbers from government schemes": "सरकारी योजनाओं से वास्तविक लाभार्थी संख्या",
    "PM Kisan Samman Nidhi": "पीएम किसान सम्मान निधि",
    "11.8 Crore+ Farmers Applied": "11.8 करोड़+ किसानों ने आवेदन किया",
    "Provides ₹6000 per year financial support directly to farmers’ bank accounts.": "किसानों के बैंक खातों में सीधे सालाना ₹6000 वित्तीय सहायता प्रदान करता है।",
    "👨‍🌾 9,50,00,000+ farmers benefited": "👨‍🌾 9,50,00,000+ किसानों ने लाभ उठाया",
    "💸 Avg Support Received: ₹6,000": "💸 औसत सहायता प्राप्त: ₹6,000",
    "⭐ Farmer Satisfaction: 4.5 / 5": "⭐ किसान संतुष्टि: 4.5 / 5",
    "Pradhan Mantri Fasal Bima Yojana": "प्रधान मंत्री फसल बीमा योजना",
    "36 Crore+ Applications": "36 करोड़+ आवेदन",
    "Protects farmers against crop loss due to drought, flood, or natural disasters.": "सूखा, बाढ़ या प्राकृतिक आपदाओं से फसल हानि से किसानों की सुरक्षा करता है।",
    "👨‍🌾 3,20,00,000+ farmers benefited": "👨‍🌾 3,20,00,000+ किसानों ने लाभ उठाया",
    "💸 Avg Claim Settled: ₹18,400": "💸 औसत दावा निपटाया: ₹18,400",
    "⭐ Farmer Satisfaction: 4.0 / 5": "⭐ किसान संतुष्टि: 4.0 / 5",
    "Kisan Credit Card (KCC)": "किसान क्रेडिट कार्ड (केसीसी)",
    "7.3 Crore+ Farmers Applied": "7.3 करोड़+ किसानों ने आवेदन किया",
    "Provides low‑interest loans for seeds, equipment, and farming needs.": "बीज, उपकरण और खेती की जरूरतों के लिए कम‑ब्याज ऋण प्रदान करता है।",
    "👨‍🌾 4,80,00,000+ farmers benefited": "👨‍🌾 4,80,00,000+ किसानों ने लाभ उठाया",
    "💸 Avg Loan Issued: ₹1,12,000": "💸 औसत ऋण जारी: ₹1,12,000",
    "⭐ Farmer Satisfaction: 4.3 / 5": "⭐ किसान संतुष्टि: 4.3 / 5",
    "Ready to Discover Your Schemes?": "क्या आप अपनी योजनाएँ जानने के लिए तैयार हैं?",
    "Join thousands of farmers who are now getting the government support they deserve.": "हजारों किसान जो अब सरकारी सहायता प्राप्त कर रहे हैं, उनमें शामिल हों।",
    "Get Started Now": "अभी शुरू करें",
    "Kisan Sahay": "किसान सहाय",
    "Empowering farmers with government support discovery.": "किसानों को सरकारी सहायता खोजने में सशक्त बनाना।",
    "Product": "उत्पाद",
    "Features": "विशेषताएँ",
    "Pricing": "मूल्य निर्धारण",
    "Blog": "ब्लॉग",
    "Company": "कंपनी",
    "About": "हमारे बारे में",
    "Contact": "संपर्क करें",
    "Careers": "करियर",
    "Legal": "कानूनी",
    "Privacy": "गोपनीयता",
    "Terms": "शर्तें",
    "Security": "सुरक्षा",
    "Twitter": "ट्विटर",
    "Facebook": "फेसबुक",
    "LinkedIn": "लिंक्डइन"
  },
  mr: {
    "Helping 2M+ farmers discover schemes": "2M+ शेतकऱ्यांना योजना शोधण्यास मदत",
    "Farmer Miss Benefits <br/> Worth  50000 Every  Year": "शेतकऱ्यांना दर वर्षी ₹50,000 पर्यंत लाभ",
    "Find all government <br/>schemes in one place": "सर्व सरकारी योजना एका ठिकाणी शोधा",
    "Continue with Mobile": "मोबाईलसह सुरू ठेवा",
    "Choose What You Need Help With": "तुम्हाला कुठल्या मदतीची गरज आहे ते निवडा",
    "Instantly discover your eligible benefits in 30 seconds": "30 सेकंदांत तुमच्या पात्र योजनांचा शोध घ्या",
    "Government Schemes": "सरकारी योजना",
    "Get ₹6,000 – ₹50,000 yearly support from government schemes": "सरकारी योजना मार्फत ₹6,000 – ₹50,000 वार्षिक मदत मिळवा",
    "PM Kisan": "पीएम किसान",
    "Subsidy Programs": "सबसिडी योजना",
    "Equipment Support": "उपकरण मदत",
    "select": "निवडा",
    "Insurance Coverage": "इन्शुरन्स कव्हरेज",
    "Protect crops & get ₹10,000 – ₹2,00,000 claim support": "पिकांचे संरक्षण करा आणि ₹10,000 – ₹2,00,000 दावा मदत मिळवा",
    "✔ Crop Insurance": "✔ पीक विमा",
    "✔ Health Coverage": "✔ आरोग्य कव्हरेज",
    "✔ Accident Protection": "✔ अपघात संरक्षण",
    "Financial Support": "आर्थिक मदत",
    "Get loans up to ₹3,00,000 at lowest interest": "कमी व्याजदरावर ₹3,00,000 पर्यंत कर्ज मिळवा",
    "✔ Kisan Credit Card": "✔ किसान क्रेडिट कार्ड",
    "✔ Farm Loans": "✔ शेती कर्ज",
    "✔ Interest Subsidy": "✔ व्याज सबसिडी",
    "How It Works": "हे कसे काम करते",
    "Three simple steps to discover your schemes": "तुमच्या योजनांचा शोध घेण्यासाठी तीन सोपे टप्पे",
    "Create Profile": "प्रोफाइल तयार करा",
    "Share basic information about your farm and eligibility criteria.": "तुमच्या शेताबाबत आणि पात्रतेची माहिती सामायिक करा.",
    "Auto Matching": "स्वयंचलित जुळणी",
    "Our system instantly matches you with all eligible government schemes.": "आमची प्रणाली तुम्हाला सर्व पात्र सरकारी योजनांशी ताबडतोब जुळवते.",
    "Apply Instantly": "तुरंत अर्ज करा",
    "Get complete guidance and apply directly through our platform.": "संपूर्ण मार्गदर्शन मिळवा आणि थेट आमच्या प्लॅटफॉर्मवरून अर्ज करा.",
    "Trusted by Millions of Farmers": "मिलियन शेतकऱ्यांनी विश्वास ठेवलाः",
    "Real adoption numbers from government schemes": "सरकारी योजना मधून वास्तविक लाभार्थी संख्या",
    "PM Kisan Samman Nidhi": "पीएम किसान सम्मान निधी",
    "11.8 Crore+ Farmers Applied": "11.8 कोटी+ शेतकऱ्यांनी अर्ज केला",
    "Provides ₹6000 per year financial support directly to farmers’ bank accounts.": "शेतकऱ्यांच्या बँक खात्यात थेट दरवर्षी ₹6000 आर्थिक मदत देते.",
    "👨‍🌾 9,50,00,000+ farmers benefited": "👨‍🌾 9,50,00,000+ शेतकऱ्यांना फायदा झाला",
    "💸 Avg Support Received: ₹6,000": "💸 सरासरी मदत प्राप्त: ₹6,000",
    "⭐ Farmer Satisfaction: 4.5 / 5": "⭐ शेतकरी समाधान: 4.5 / 5",
    "Pradhan Mantri Fasal Bima Yojana": "प्रधान मंत्री फसल विमा योजना",
    "36 Crore+ Applications": "36 कोटी+ अर्ज",
    "Protects farmers against crop loss due to drought, flood, or natural disasters.": "सुकाम, पूर किंवा नैसर्गिक आपत्तींमुळे पिकांची हानी रोखते.",
    "👨‍🌾 3,20,00,000+ farmers benefited": "👨‍🌾 3,20,00,000+ शेतकऱ्यांना फायदा झाला",
    "💸 Avg Claim Settled: ₹18,400": "💸 सरासरी दावा निपटवला: ₹18,400",
    "⭐ Farmer Satisfaction: 4.0 / 5": "⭐ शेतकरी समाधान: 4.0 / 5",
    "Kisan Credit Card (KCC)": "किसान क्रेडिट कार्ड (KCC)",
    "7.3 Crore+ Farmers Applied": "7.3 कोटी+ शेतकऱ्यांनी अर्ज केला",
    "Provides low‑interest loans for seeds, equipment, and farming needs.": "बीज, उपकरण आणि शेतीसाठी कमी व्याजदराचे कर्ज देते.",
    "👨‍🌾 4,80,00,000+ farmers benefited": "👨‍🌾 4,80,00,000+ शेतकऱ्यांना फायदा झाला",
    "💸 Avg Loan Issued: ₹1,12,000": "💸 सरासरी कर्ज जारी: ₹1,12,000",
    "⭐ Farmer Satisfaction: 4.3 / 5": "⭐ शेतकरी समाधान: 4.3 / 5",
    "Ready to Discover Your Schemes?": "तुमच्या योजनांचा शोध घेण्यासाठी तयार आहात?",
    "Join thousands of farmers who are now getting the government support they deserve.": "हजारो शेतकरी जे आता सरकारी मदत मिळवत आहेत त्यात सामील व्हा.",
    "Get Started Now": "आता प्रारंभ करा",
    "Kisan Sahay": "किसान सहाय",
    "Empowering farmers with government support discovery.": "शेतकऱ्यांना सरकारी मदत शोधण्यात सशक्त करणे.",
    "Product": "उत्पादन",
    "Features": "वैशिष्ट्ये",
    "Pricing": "किंमत",
    "Blog": "ब्लॉग",
    "Company": "कंपनी",
    "About": "आमच्याबद्दल",
    "Contact": "संपर्क",
    "Careers": "करिअर",
    "Legal": "कायदेशीर",
    "Privacy": "गोपनीयता",
    "Terms": "अटी",
    "Security": "सुरक्षा",
    "Twitter": "ट्विटर",
    "Facebook": "फेसबुक",
    "LinkedIn": "लिंक्डइन"
  }
};


  const t = (key: string) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
