export const STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Dadra and Nagar Haveli',
  'Daman and Diu',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
]

export const DISTRICTS: Record<string, string[]> = {
  'Andhra Pradesh': [
    'Visakhapatnam',
    'Vijaywada',
    'Guntur',
    'Krishna',
    'Prakasam',
    'Kurnool',
    'Nellore',
    'Chittoor',
    'Anantapur',
    'Kadapa',
    'Nanded',
  ],
  'Arunachal Pradesh': [
    'Papum Pare',
    'Changlang',
    'Lohit',
    'West Kameng',
    'East Kameng',
    'Tawang',
    'Dibang Valley',
    'Kurung Kumey',
  ],
  Assam: [
    'Kamrup',
    'Nagaon',
    'Sonitpur',
    'Barpeta',
    'Dhubri',
    'Goalpara',
    'Silchar',
    'Cachar',
    'Karimganj',
    'Nowgong',
    'Sibsagar',
    'Jorhat',
    'Dibrugarh',
  ],
  Bihar: [
    'Patna',
    'East Champaran',
    'West Champaran',
    'Muzaffarpur',
    'Madhubani',
    'Darbhanga',
    'Supaul',
    'Saharsa',
    'Purnea',
    'Katihar',
    'Araria',
    'Gaya',
    'Jehanabad',
    'Nalanda',
    'Nawada',
  ],
  Chhattisgarh: [
    'Durg',
    'Raipur',
    'Bilaspur',
    'Rajnandgaon',
    'Dhamtari',
    'Kanker',
    'Bastar',
    'Jagdalpur',
    'Korba',
  ],
  'Dadra and Nagar Haveli': ['Silvassa'],
  'Daman and Diu': ['Daman', 'Diu'],
  Goa: ['North Goa', 'South Goa'],
  Gujarat: [
    'Ahmedabad',
    'Vadodara',
    'Surat',
    'Rajkot',
    'Junagadh',
    'Jamnagar',
    'Bhavnagar',
    'Anand',
    'Kheda',
    'Panchmahal',
    'Sabarkantha',
    'Gandhinagar',
    'Surendranagar',
    'Amreli',
    'Porbandar',
  ],
  Haryana: [
    'Hisar',
    'Rohtak',
    'Faridabad',
    'Karnal',
    'Sonipat',
    'Panipat',
    'Ambala',
    'Kurukshetra',
    'Yamunanagar',
    'Jind',
    'Sirsa',
    'Nuh',
  ],
  'Himachal Pradesh': [
    'Kangra',
    'Solan',
    'Shimla',
    'Mandi',
    'Kinnaur',
    'Lahaul and Spiti',
    'Hamirpur',
    'Una',
    'Bilaspur',
    'Chamba',
  ],
  Jharkhand: [
    'Ranchi',
    'Dhanbad',
    'Giridih',
    'Purnia',
    'Hazaribagh',
    'Dumka',
    'Godda',
    'Koderma',
    'Pakur',
    'Deoghar',
    'Jamtara',
    'East Singhbhum',
    'West Singhbhum',
  ],
  Karnataka: [
    'Bangalore',
    'Belgaum',
    'Mysore',
    'Mangalore',
    'Davanagere',
    'Tumkur',
    'Chikmagalur',
    'Hassan',
    'Kolar',
    'Shimoga',
    'Bijapur',
    'Bagalkot',
    'Gulbarga',
  ],
  Kerala: [
    'Ernakulam',
    'Thiruvananthapuram',
    'Kozhikode',
    'Kottayam',
    'Thrissur',
    'Pathanamthitta',
    'Alappuzha',
    'Idukki',
    'Palakkad',
    'Malappuram',
    'Kasaragod',
    'Wayanad',
  ],
  'Madhya Pradesh': [
    'Indore',
    'Bhopal',
    'Jabalpur',
    'Gwalior',
    'Ujjain',
    'Ratlam',
    'Dewas',
    'Dhar',
    'Khargone',
    'Betul',
    'Chhindwara',
    'Seoni',
    'Mandla',
    'Balaghat',
    'Shahdol',
    'Umaria',
  ],
  Maharashtra: [
    'Mumbai',
    'Pune',
    'Nagpur',
    'Aurangabad',
    'Nashik',
    'Ahmednagar',
    'Solapur',
    'Sangli',
    'Kolhapur',
    'Satara',
    'Ratnagiri',
    'Sindhudurg',
    'Thane',
    'Raigad',
    'Jalgaon',
    'Dhule',
  ],
  Manipur: ['Imphal East', 'Imphal West', 'Bishnupur', 'Thoubal', 'Chandel', 'Senapati'],
  Meghalaya: ['Shillong', 'East Khasi Hills', 'West Khasi Hills', 'Jaintia Hills'],
  Mizoram: ['Aizawl', 'Lunglei', 'Champhai', 'Serchhip', 'Mamit'],
  Nagaland: ['Kohima', 'Dimapur', 'Mon', 'Zunheboto', 'Wokha', 'Mokokchung'],
  Odisha: [
    'Cuttack',
    'Rourkela',
    'Bolangir',
    'Balangir',
    'Dhenkanal',
    'Angul',
    'Sambalpur',
    'Bargarh',
    'Kendujhar',
  ],
  Puducherry: ['Puducherry', 'Yanam', 'Mahe', 'Karaikal'],
  Punjab: [
    'Amritsar',
    'Ludhiana',
    'Jalandhar',
    'Patiala',
    'Hoshiarpur',
    'Pathankot',
    'Moga',
    'Bathinda',
    'Firozpur',
    'Rupnagar',
  ],
  Rajasthan: [
    'Jaipur',
    'Jodhpur',
    'Udaipur',
    'Bikaner',
    'Ajmer',
    'Alwar',
    'Banswara',
    'Barmer',
    'Beawar',
    'Bhilwara',
    'Ganganagar',
    'Nagaur',
    'Pali',
    'Sikar',
  ],
  Sikkim: ['East Sikkim', 'West Sikkim', 'South Sikkim', 'North Sikkim'],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli',
    'Salam',
    'Dindigul',
    'Tirunelveli',
    'Kanyakumari',
    'Vellore',
    'Villupuram',
    'Tiruvannamalai',
    'Cuddalore',
    'Erode',
    'Namakkal',
    'Salem',
    'Nilgiris',
  ],
  Telangana: [
    'Hyderabad',
    'Warangal',
    'Nizamabad',
    'Karimnagar',
    'Khammam',
    'Mahbubnagar',
    'Ranga Reddy',
    'Medak',
  ],
  Tripura: ['West Tripura', 'South Tripura', 'Dhalai', 'North Tripura'],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur',
    'Varanasi',
    'Agra',
    'Meerut',
    'Ghaziabad',
    'Noida',
    'Allahabad',
    'Bareilly',
    'Moradabad',
    'Aligarh',
    'Firozabad',
    'Mathura',
    'Ayodhya',
    'Jhansi',
    'Gwalior',
  ],
  Uttarakhand: [
    'Dehradun',
    'Haridwar',
    'Nainital',
    'Almora',
    'Bageshwar',
    'Chamoli',
    'Garhwal',
    'Pithoragarh',
    'Rudraprayag',
  ],
  'West Bengal': [
    'Kolkata',
    'Darjeeling',
    'Jalpaiguri',
    'Cooch Behar',
    'Alipurduar',
    'Malda',
    'Murshidabad',
    'Birbhum',
    'Purulia',
    'Bankura',
    'Burdwan',
    'Nadia',
    'Uttar Dinajpur',
    'Dakshin Dinajpur',
  ],
  Ladakh: ['Leh', 'Kargil'],
  Lakshadweep: ['Lakshadweep'],
}

export const LAND_OWNERSHIP_TYPES = ['Own', 'Leased', 'Shared', 'Other']

export const LAND_SIZES = [
  '< 0.5 hectare',
  '0.5-1 hectare',
  '1-2 hectares',
  '2-5 hectares',
  '5-10 hectares',
  '> 10 hectares',
]

export const CROP_TYPES = [
  'Rice',
  'Wheat',
  'Maize',
  'Cotton',
  'Sugarcane',
  'Vegetables',
  'Fruits',
  'Pulses',
  'Spices',
  'Oilseeds',
  'Tea',
  'Coffee',
  'Horticulture',
  'Mixed Cropping',
  'Other',
]

export const ANNUAL_INCOME_RANGES = [
  'Below ₹50,000',
  '₹50,000 - ₹1,00,000',
  '₹1,00,000 - ₹2,50,000',
  '₹2,50,000 - ₹5,00,000',
  '₹5,00,000 - ₹10,00,000',
  'Above ₹10,00,000',
]

export const FARMER_CATEGORIES = [
  'Marginal Farmer (< 1 hectare)',
  'Small Farmer (1-2 hectares)',
  'Medium Farmer (2-10 hectares)',
  'Large Farmer (> 10 hectares)',
  'Woman Farmer',
  'SC/ST Farmer',
  'Youth Farmer (below 35)',
  'Senior Farmer (above 60)',
  'First-time Farmer',
]

export const FARMING_SEASONS = [
  'Kharif (June - October)',
  'Rabi (October - March)',
  'Zaid (March - June)',
  'Year-round',
]
